# Generated by Django 5.0.1 on 2024-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
